[build]
builder = "nixpacks"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["python3", "gcc", "gnumake"]

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
